services:
  - type: web
    name: perplexity-clone-api
    env: python
    repo: https://github.com/k3tikvats/perplexity_clone.git
    rootDir: server
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    plan: starter
